# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import sys

connection = mysql.connector.connect(host='localhost', user='root', password='x132131x', db='db_accounts')
cursor = connection.cursor()
regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
error = True

class Login_Window(object):
    global error
    def login(self): 
        def showMessage(message):
                self.frame_error.show()   
                self.label_error.setText(message)
                self.frame_error.setStyleSheet("QFrame {\n"
                "background-color: rgb(201, 8, 8);\n"
                "border-radius: 5px;\n"
                "}\n")
        get_datas = "select * from tb_accounts"
        cursor.execute(get_datas)
        lines = cursor.fetchall()
        text = ''
        flag = False
        for line in lines:
                if (line[1] == self.LineEdit_User.text() or line[3] == self.LineEdit_User.text()) and line[2] == self.LineEdit_Password.text():
                        flag = True
                else:
                        text = 'Senha e/ou Usuário incorreto(s)'
                        showMessage(text)
                        error = True
                if flag:
                        print('Logado com sucesso')
                        error = False
        return error
        


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setStyleSheet("color: rgb(200, 200, 200);\n"
        "background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.top_bar)
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(255, 14, 18);\n"
        "border-radius: 5px;\n"
        "")
        self.frame_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 3, 10)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.bt_close = QtWidgets.QPushButton(self.frame_error)
        self.bt_close.setMaximumSize(QtCore.QSize(20, 20))
        self.bt_close.setStyleSheet("QPushButton {\n"
        "    background-image: url(:/Close_Image/cil-x.png);\n"
        "    border-radius: 5px;\n"
        "    background-position: center;\n"
        "    background-color: rgb(60, 60, 60);\n"
        "}\n"
        "QPushButton:hover {\n"
        "    color: rgb(200, 200, 200);\n"
        "    background-color:rgb(50, 50, 50);\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    color: rgb(200, 200, 200);\n"
        "    background-color:rgb(35, 35, 35);\n"
        "}")
        self.bt_close.setText("")
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_3.addWidget(self.bt_close)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_area = QtWidgets.QFrame(self.content)
        self.login_area.setMaximumSize(QtCore.QSize(450, 550))
        self.login_area.setStyleSheet("background-color: rgb(30, 30, 30);\n"
        "border-radius: 10px solid;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.LineEdit_User = QtWidgets.QLineEdit(self.login_area)
        self.LineEdit_User.setGeometry(QtCore.QRect(85, 260, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LineEdit_User.setFont(font)
        self.LineEdit_User.setStyleSheet("QLineEdit {\n"
        "    border: 2px solid rgb(45, 45, 45);\n"
        "    border-radius: 5px;\n"
        "    padding: 15px;\n"
        "    background-color: rgb(30, 30, 30);\n"
        "    color: rgb(100, 100, 100);\n"
        "}\n"
        "\n"
        "QLineEdit:hover {\n"
        "    border: 2px solid rgb(55, 55, 55);\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid rgb(255, 207, 0);\n"
        "    color: rgb(200, 200, 200);\n"
        "}")
        self.LineEdit_User.setMaxLength(32)
        self.LineEdit_User.setObjectName("LineEdit_User")
        self.LineEdit_Password = QtWidgets.QLineEdit(self.login_area)
        self.LineEdit_Password.setGeometry(QtCore.QRect(85, 320, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LineEdit_Password.setFont(font)
        self.LineEdit_Password.setStyleSheet("QLineEdit {\n"
        "    border: 2px solid rgb(45, 45, 45);\n"
        "    border-radius: 5px;\n"
        "    padding: 15px;\n"
        "    background-color: rgb(30, 30, 30);\n"
        "    color: rgb(100, 100, 100);\n"
        "}\n"
        "\n"
        "QLineEdit:hover {\n"
        "    border: 2px solid rgb(55, 55, 55);\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid rgb(255, 207, 0);\n"
        "    color: rgb(200, 200, 200);\n"
        "}")
        self.LineEdit_Password.setMaxLength(16)
        self.LineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LineEdit_Password.setObjectName("LineEdit_Password")
        self.Bt_register = QtWidgets.QPushButton(self.login_area)
        self.Bt_register.setGeometry(QtCore.QRect(85, 380, 280, 25))
        self.Bt_register.setStyleSheet("QPushButton {\n"
        "    background-color: rgb(50, 50, 50);\n"
        "    border: 2px solid rgb(60, 60, 60);\n"
        "    border-radius: 5px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: rgb(60, 60, 60);\n"
        "    border: 2px solid rgb(70, 70, 70);\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: rgb(250, 230, 0);\n"
        "    border: 2px solid rgb(255, 165, 24);\n"
        "    color: rgb(35, 35, 35);\n"
        "}")
        self.Bt_register.setObjectName("Bt_register")
        self.checkBox = QtWidgets.QCheckBox(self.login_area)
        self.checkBox.setGeometry(QtCore.QRect(85, 405, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
        "    border: 3px solid rgb(100, 100, 100);\n"
        "    width: 15px;\n"
        "    height: 15px;\n"
        "    border-radius: 10px;\n"
        "    background-color: rgb(135, 135, 135);\n"
        "}\n"
        "\n"
        "QCheckBox::indicator:checked {\n"
        "    border: 3px solid rgb(255, 205, 0);\n"
        "    background-color: rgb(255, 255, 0);\n"
        "}")
        self.checkBox.setObjectName("checkBox")
        self.Bt_login = QtWidgets.QPushButton(self.login_area)
        self.Bt_login.setGeometry(QtCore.QRect(85, 450, 280, 50))
        self.Bt_login.setStyleSheet("QPushButton {\n"
        "    background-color: rgb(50, 50, 50);\n"
        "    border: 2px solid rgb(60, 60, 60);\n"
        "    border-radius: 5px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: rgb(60, 60, 60);\n"
        "    border: 2px solid rgb(70, 70, 70);\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: rgb(250, 230, 0);\n"
        "    border: 2px solid rgb(255, 165, 24);\n"
        "    color: rgb(35, 35, 35);\n"
        "}")
        self.Bt_login.setObjectName("Bt_login")
        self.horizontalLayout.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom_bar_2 = QtWidgets.QFrame(self.centralwidget)
        self.bottom_bar_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom_bar_2.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom_bar_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_bar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_bar_2.setObjectName("bottom_bar_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_bar_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.bottom_bar_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(75, 75, 75);\n"
        "background-color: rgb(15, 15, 15);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.bottom_bar_2)
        MainWindow.setCentralWidget(self.centralwidget)

        #
        #Functions
        #

        #Button close Popup
        self.bt_close.clicked.connect(lambda: self.frame_error.hide())
        #Hide popup
        self.frame_error.hide()

        #Buton login
        self.Bt_login.clicked.connect(self.login)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login menu"))
        self.label_error.setText(_translate("MainWindow", "SENHA OU USUÁRIO INVÁLIDO(S)"))
        self.LineEdit_User.setPlaceholderText(_translate("MainWindow", "USER/EMAIL"))
        self.LineEdit_Password.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.Bt_register.setText(_translate("self", "CLIQUE AQUI CASO AINDA NÃO TENHA SE REGISTRADO"))
        self.checkBox.setText(_translate("MainWindow", "SAVE USER"))
        self.Bt_login.setText(_translate("MainWindow", "LOGIN"))
        self.label.setText(_translate("MainWindow", "Created by: Nicolas Becker and Pedro"))
import files_rc

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Login_Window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
    
